server.port=8080

spring.application.name=smart-log-analyzer
spring.main.web-application-type=reactive

logging.level.root=INFO
logging.level.reactor.netty=INFO

stream.log-interval-ms=1000

ai.provider=openai

ai.openai.api-key=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
ai.openai.model=gpt-4o-mini
