server.port=8080

spring.application.name=smart-log-analyzer
spring.main.web-application-type=reactive

logging.level.root=INFO
logging.level.reactor.netty=INFO

stream.log-interval-ms=1000

ai.provider=openai

ai.openai.api-key=${OPENAI_API_KEY}
ai.openai.model=gpt-4o-mini
